ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.activity_logs AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.activity_logs AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.activity_logs AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.activity_logs AS PERMISSIVE FOR UPDATE TO public USING (true);
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.appointments AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.appointments AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.appointments AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.appointments AS PERMISSIVE FOR UPDATE TO public USING (true);
ALTER TABLE public.automations ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.automations AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.automations ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.automations AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.automations ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.automations AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.automations ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.automations AS PERMISSIVE FOR UPDATE TO public USING (true);
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.campaigns AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.campaigns AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.campaigns AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.campaigns AS PERMISSIVE FOR UPDATE TO public USING (true);
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.doctors AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.doctors AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.doctors AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.doctors AS PERMISSIVE FOR UPDATE TO public USING (true);
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.invoices AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.invoices AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.invoices AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.invoices AS PERMISSIVE FOR UPDATE TO public USING (true);
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.leads AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.leads AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.leads AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.leads AS PERMISSIVE FOR UPDATE TO public USING (true);
ALTER TABLE public.memberships ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.memberships AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.memberships ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.memberships AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.memberships ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.memberships AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.memberships ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.memberships AS PERMISSIVE FOR UPDATE TO public USING (true);
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.messages AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.messages AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.messages AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.messages AS PERMISSIVE FOR UPDATE TO public USING (true);
ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.packages AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.packages AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.packages AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.packages AS PERMISSIVE FOR UPDATE TO public USING (true);
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.patients AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.patients AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.patients AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.patients AS PERMISSIVE FOR UPDATE TO public USING (true);
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.reviews AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.reviews AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.reviews AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.reviews AS PERMISSIVE FOR UPDATE TO public USING (true);
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.settings AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.settings AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.settings AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.settings AS PERMISSIVE FOR UPDATE TO public USING (true);
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.staff AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.staff AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.staff AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.staff AS PERMISSIVE FOR UPDATE TO public USING (true);
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_delete ON public.tasks AS PERMISSIVE FOR DELETE TO public USING (true);
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_insert ON public.tasks AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_select ON public.tasks AS PERMISSIVE FOR SELECT TO public USING (true);
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY demo_all_update ON public.tasks AS PERMISSIVE FOR UPDATE TO public USING (true);
