CREATE UNIQUE INDEX activity_logs_pkey ON public.activity_logs USING btree (id);
CREATE UNIQUE INDEX appointments_pkey ON public.appointments USING btree (id);
CREATE INDEX idx_appts_scheduled ON public.appointments USING btree (scheduled_at);
CREATE INDEX idx_appts_status ON public.appointments USING btree (status);
CREATE UNIQUE INDEX automations_pkey ON public.automations USING btree (id);
CREATE UNIQUE INDEX campaigns_pkey ON public.campaigns USING btree (id);
CREATE UNIQUE INDEX doctors_pkey ON public.doctors USING btree (id);
CREATE INDEX idx_invoices_created ON public.invoices USING btree (created_at);
CREATE UNIQUE INDEX invoices_invoice_no_key ON public.invoices USING btree (invoice_no);
CREATE UNIQUE INDEX invoices_pkey ON public.invoices USING btree (id);
CREATE UNIQUE INDEX leads_pkey ON public.leads USING btree (id);
CREATE UNIQUE INDEX memberships_pkey ON public.memberships USING btree (id);
CREATE INDEX idx_messages_patient ON public.messages USING btree (patient_id);
CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);
CREATE UNIQUE INDEX packages_pkey ON public.packages USING btree (id);
CREATE INDEX idx_patients_status ON public.patients USING btree (status);
CREATE UNIQUE INDEX patients_pkey ON public.patients USING btree (id);
CREATE UNIQUE INDEX reviews_pkey ON public.reviews USING btree (id);
CREATE UNIQUE INDEX settings_pkey ON public.settings USING btree (id);
CREATE UNIQUE INDEX staff_pkey ON public.staff USING btree (id);
CREATE UNIQUE INDEX tasks_pkey ON public.tasks USING btree (id);
